name: entlens
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6.5
  - numpy
  - nltk
  - pyyaml
  - matplotlib
  - pytorch=1.0.0
  - pillow
  - scipy
  - scikit-learn=0.20.2
  - pip:
    - tqdm
    - torchvision
    - ipdb